package cg.base.io;

public interface Opcode {
	
	byte NO_SERIAL = -1;
	
	
	byte HEART_BEAT_CLIENT = 1;
	
	byte HEART_BEAT_SERVER = 2;
	
	byte DISCONNECTED_CLIENT = 3;
	
	byte PROXY_SESSION_DISCONNECT = 6;
	
	byte PROXY_SYNC_IP = 7;
	
	byte PROXY_LOGIN = 8;
	
	byte SERVER_EXECUTE_OK = 9;
	
	byte SERVER_EXECUTE_ERROR = 10;
	
	
	byte ACCOUNT_REGISTER_CLIENT = 11;
	
	byte ACCOUNT_REGISTER_SERVER = 12;
	
	byte ACCOUNT_LOGIN_CLIENT = 13;
	
	byte ACCOUNT_LOGIN_SERVER = 14;
	
	byte ACCOUNT_ROLE_LIST_CLIENT = 15;
	
	byte ACCOUNT_ROLE_LIST_SERVER = 16;
	
	byte SERVER_LIST_CLIENT = 17;
	
	byte SERVER_LIST_SERVER = 18;
	
	byte SERVER_SELECT_CLIENT = 19;
	
	byte SERVER_SELECT_SERVER = 20;
	
	byte ACCOUNT_LOGOUT_CLIENT = 21;
	
	byte ACCOUNT_LOGOUT_SERVER = 22;
	
	byte ACCOUNT_CHANGE_PASSWORD_CLIENT = 23;
	
	byte ACCOUNT_CHANGE_PASSWORD_SERVER = 24;
	
	
	byte PLAYER_CREATE_CLIENT = 31;
	
	byte PLAYER_DELETE_CLIENT = 32;
	
	byte PLAYER_QUERY_CLIENT = 33;
	
	byte PLAYER_QUERY_SERVER = 34;
	
	byte PLAYER_LOGIN_CLIENT = 35;
	
	byte PLAYER_LOGIN_SERVER = 36;
	
	byte PLAYER_CREATE_INFO_CLIENT = 37;
	
	byte PLAYER_CREATE_INFO_SERVER = 38;
	
	byte PLAYER_ANIMATION_INFO_CLIENT = 39;
	
	byte PLAYER_ANIMATION_INFO_SERVER = 40;
	
	
	byte MAP_IN_CLIENT = 51;
	
	byte MAP_IN_SERVER = 52;
	
	byte MAP_MOVE_CLIENT = 53;
	
	byte MAP_MOVE_SERVER = 54;
	
	byte MAP_MOVE_FINISH_CLIENT = 55;
	
	byte MAP_UNIT_CREATE_SERVER = 58;
	
	byte MAP_UNIT_MOVE_SERVER = 60;
	
	byte MAP_UNIT_REMOVE_SERVER = 62;
	
	byte MAP_CELLS_CLIENT = 63;
	
	byte MAP_CELLS_SERVER = 64;
	
	byte MAP_LOAD_FINISH_CLIENT = 65;
	
	byte MAP_LOAD_FINISH_SERVER = 66;
	
	
	byte BATTLE_ENTER_SERVER = 72;
	
	byte BATTLE_ATTACK_CLIENT = 73;
	
	byte BATTLE_ACTION_SERVER = 76;
	
	byte BATTLE_DEFEND_CLIENT = 77;
	
	byte BATTLE_WAIT_COMMAND_SERVER = 80;
	
	byte BATTLE_ANIMATION_FINISH = 81;
	
	byte BATTLE_FINISH_SERVER = 84;
	
	
	byte SCRIPT_SERVER = 102;
	
	byte SCRIPT_MUTUAL_CLIENT = 103;
	
	byte SCRIPT_MUTUAL_SERVER = 104;
	
	byte SCRIPT_ERROR_SERVER = 106;
	
	
	short CHAT_CLIENT = 141;
	
	short CHAT_SERVER = 142;
	
	short CHAT_JOIN_CLIENT = 143;
	
	short CHAT_JOIN_SERVER = 144;
	
	short CHAT_LEAVE_CLIENT = 145;
	
	short CHAT_LEAVE_SERVER = 146;
	
	
	short SKILL_USE_CLIENT = 161;
	
	short RECIPE_CLIENT = 163;
	
	short DOUBLE_EXP_BEGIN_CLIENT = 165;
	
	short DOUBLE_EXP_END_CLIENT = 167;
	
	short DOUBLE_EXP_END_SERVER = 168;
	
	short DOUBLE_EXP_UPDATE_CLIENT = 169;
	
	short DOUBLE_EXP_UPDATE_SERVER = 170;
	
	short SKILL_LEARN_CLIENT = 171;
	
	short SKILL_LEARN_SERVER = 172;
	
	short SKILL_UNLEARN_CLIENT = 173;
	
	short SKILL_UNLEARN_SERVER = 174;
	
	
	short MAIL_SEND_SERVER = 202;
	
	
	short OPTIONS_SET_CLIENT = 241;
	
	short OPTIONS_SET_SERVER = 242;

}
