// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

package cg.base.io.proto;

public final class ChatProtos {
  private ChatProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface REQUEST_CHATOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 channel = 1;
    /**
     * <code>required int32 channel = 1;</code>
     */
    boolean hasChannel();
    /**
     * <code>required int32 channel = 1;</code>
     */
    int getChannel();

    // required int32 targetId = 2;
    /**
     * <code>required int32 targetId = 2;</code>
     */
    boolean hasTargetId();
    /**
     * <code>required int32 targetId = 2;</code>
     */
    int getTargetId();

    // required string text = 3;
    /**
     * <code>required string text = 3;</code>
     */
    boolean hasText();
    /**
     * <code>required string text = 3;</code>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 3;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code REQUEST_CHAT}
   */
  public static final class REQUEST_CHAT extends
      com.google.protobuf.GeneratedMessage
      implements REQUEST_CHATOrBuilder {
    // Use REQUEST_CHAT.newBuilder() to construct.
    private REQUEST_CHAT(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private REQUEST_CHAT(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final REQUEST_CHAT defaultInstance;
    public static REQUEST_CHAT getDefaultInstance() {
      return defaultInstance;
    }

    public REQUEST_CHAT getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private REQUEST_CHAT(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              channel_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              targetId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              text_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cg.base.io.proto.ChatProtos.internal_static_REQUEST_CHAT_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cg.base.io.proto.ChatProtos.internal_static_REQUEST_CHAT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cg.base.io.proto.ChatProtos.REQUEST_CHAT.class, cg.base.io.proto.ChatProtos.REQUEST_CHAT.Builder.class);
    }

    public static com.google.protobuf.Parser<REQUEST_CHAT> PARSER =
        new com.google.protobuf.AbstractParser<REQUEST_CHAT>() {
      public REQUEST_CHAT parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new REQUEST_CHAT(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<REQUEST_CHAT> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 channel = 1;
    public static final int CHANNEL_FIELD_NUMBER = 1;
    private int channel_;
    /**
     * <code>required int32 channel = 1;</code>
     */
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 channel = 1;</code>
     */
    public int getChannel() {
      return channel_;
    }

    // required int32 targetId = 2;
    public static final int TARGETID_FIELD_NUMBER = 2;
    private int targetId_;
    /**
     * <code>required int32 targetId = 2;</code>
     */
    public boolean hasTargetId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 targetId = 2;</code>
     */
    public int getTargetId() {
      return targetId_;
    }

    // required string text = 3;
    public static final int TEXT_FIELD_NUMBER = 3;
    private java.lang.Object text_;
    /**
     * <code>required string text = 3;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string text = 3;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      channel_ = 0;
      targetId_ = 0;
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasChannel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTargetId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, channel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, targetId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, channel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, targetId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cg.base.io.proto.ChatProtos.REQUEST_CHAT parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cg.base.io.proto.ChatProtos.REQUEST_CHAT parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cg.base.io.proto.ChatProtos.REQUEST_CHAT parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cg.base.io.proto.ChatProtos.REQUEST_CHAT parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cg.base.io.proto.ChatProtos.REQUEST_CHAT parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cg.base.io.proto.ChatProtos.REQUEST_CHAT parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cg.base.io.proto.ChatProtos.REQUEST_CHAT parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cg.base.io.proto.ChatProtos.REQUEST_CHAT parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cg.base.io.proto.ChatProtos.REQUEST_CHAT parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cg.base.io.proto.ChatProtos.REQUEST_CHAT parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cg.base.io.proto.ChatProtos.REQUEST_CHAT prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code REQUEST_CHAT}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cg.base.io.proto.ChatProtos.REQUEST_CHATOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cg.base.io.proto.ChatProtos.internal_static_REQUEST_CHAT_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cg.base.io.proto.ChatProtos.internal_static_REQUEST_CHAT_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cg.base.io.proto.ChatProtos.REQUEST_CHAT.class, cg.base.io.proto.ChatProtos.REQUEST_CHAT.Builder.class);
      }

      // Construct using cg.base.io.proto.ChatProtos.REQUEST_CHAT.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        channel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        targetId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cg.base.io.proto.ChatProtos.internal_static_REQUEST_CHAT_descriptor;
      }

      public cg.base.io.proto.ChatProtos.REQUEST_CHAT getDefaultInstanceForType() {
        return cg.base.io.proto.ChatProtos.REQUEST_CHAT.getDefaultInstance();
      }

      public cg.base.io.proto.ChatProtos.REQUEST_CHAT build() {
        cg.base.io.proto.ChatProtos.REQUEST_CHAT result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cg.base.io.proto.ChatProtos.REQUEST_CHAT buildPartial() {
        cg.base.io.proto.ChatProtos.REQUEST_CHAT result = new cg.base.io.proto.ChatProtos.REQUEST_CHAT(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.channel_ = channel_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.targetId_ = targetId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cg.base.io.proto.ChatProtos.REQUEST_CHAT) {
          return mergeFrom((cg.base.io.proto.ChatProtos.REQUEST_CHAT)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cg.base.io.proto.ChatProtos.REQUEST_CHAT other) {
        if (other == cg.base.io.proto.ChatProtos.REQUEST_CHAT.getDefaultInstance()) return this;
        if (other.hasChannel()) {
          setChannel(other.getChannel());
        }
        if (other.hasTargetId()) {
          setTargetId(other.getTargetId());
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000004;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasChannel()) {
          
          return false;
        }
        if (!hasTargetId()) {
          
          return false;
        }
        if (!hasText()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cg.base.io.proto.ChatProtos.REQUEST_CHAT parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cg.base.io.proto.ChatProtos.REQUEST_CHAT) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 channel = 1;
      private int channel_ ;
      /**
       * <code>required int32 channel = 1;</code>
       */
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 channel = 1;</code>
       */
      public int getChannel() {
        return channel_;
      }
      /**
       * <code>required int32 channel = 1;</code>
       */
      public Builder setChannel(int value) {
        bitField0_ |= 0x00000001;
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 channel = 1;</code>
       */
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        channel_ = 0;
        onChanged();
        return this;
      }

      // required int32 targetId = 2;
      private int targetId_ ;
      /**
       * <code>required int32 targetId = 2;</code>
       */
      public boolean hasTargetId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 targetId = 2;</code>
       */
      public int getTargetId() {
        return targetId_;
      }
      /**
       * <code>required int32 targetId = 2;</code>
       */
      public Builder setTargetId(int value) {
        bitField0_ |= 0x00000002;
        targetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 targetId = 2;</code>
       */
      public Builder clearTargetId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        targetId_ = 0;
        onChanged();
        return this;
      }

      // required string text = 3;
      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 3;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string text = 3;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 3;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 3;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 3;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:REQUEST_CHAT)
    }

    static {
      defaultInstance = new REQUEST_CHAT(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:REQUEST_CHAT)
  }

  public interface RESPONSE_CHATOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 channel = 1;
    /**
     * <code>required int32 channel = 1;</code>
     */
    boolean hasChannel();
    /**
     * <code>required int32 channel = 1;</code>
     */
    int getChannel();

    // required int32 sourceId = 2;
    /**
     * <code>required int32 sourceId = 2;</code>
     */
    boolean hasSourceId();
    /**
     * <code>required int32 sourceId = 2;</code>
     */
    int getSourceId();

    // required string souceName = 3;
    /**
     * <code>required string souceName = 3;</code>
     */
    boolean hasSouceName();
    /**
     * <code>required string souceName = 3;</code>
     */
    java.lang.String getSouceName();
    /**
     * <code>required string souceName = 3;</code>
     */
    com.google.protobuf.ByteString
        getSouceNameBytes();

    // required string text = 4;
    /**
     * <code>required string text = 4;</code>
     */
    boolean hasText();
    /**
     * <code>required string text = 4;</code>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 4;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code RESPONSE_CHAT}
   */
  public static final class RESPONSE_CHAT extends
      com.google.protobuf.GeneratedMessage
      implements RESPONSE_CHATOrBuilder {
    // Use RESPONSE_CHAT.newBuilder() to construct.
    private RESPONSE_CHAT(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RESPONSE_CHAT(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RESPONSE_CHAT defaultInstance;
    public static RESPONSE_CHAT getDefaultInstance() {
      return defaultInstance;
    }

    public RESPONSE_CHAT getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RESPONSE_CHAT(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              channel_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sourceId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              souceName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              text_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cg.base.io.proto.ChatProtos.internal_static_RESPONSE_CHAT_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cg.base.io.proto.ChatProtos.internal_static_RESPONSE_CHAT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cg.base.io.proto.ChatProtos.RESPONSE_CHAT.class, cg.base.io.proto.ChatProtos.RESPONSE_CHAT.Builder.class);
    }

    public static com.google.protobuf.Parser<RESPONSE_CHAT> PARSER =
        new com.google.protobuf.AbstractParser<RESPONSE_CHAT>() {
      public RESPONSE_CHAT parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RESPONSE_CHAT(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RESPONSE_CHAT> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 channel = 1;
    public static final int CHANNEL_FIELD_NUMBER = 1;
    private int channel_;
    /**
     * <code>required int32 channel = 1;</code>
     */
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 channel = 1;</code>
     */
    public int getChannel() {
      return channel_;
    }

    // required int32 sourceId = 2;
    public static final int SOURCEID_FIELD_NUMBER = 2;
    private int sourceId_;
    /**
     * <code>required int32 sourceId = 2;</code>
     */
    public boolean hasSourceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 sourceId = 2;</code>
     */
    public int getSourceId() {
      return sourceId_;
    }

    // required string souceName = 3;
    public static final int SOUCENAME_FIELD_NUMBER = 3;
    private java.lang.Object souceName_;
    /**
     * <code>required string souceName = 3;</code>
     */
    public boolean hasSouceName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string souceName = 3;</code>
     */
    public java.lang.String getSouceName() {
      java.lang.Object ref = souceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          souceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string souceName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSouceNameBytes() {
      java.lang.Object ref = souceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        souceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string text = 4;
    public static final int TEXT_FIELD_NUMBER = 4;
    private java.lang.Object text_;
    /**
     * <code>required string text = 4;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string text = 4;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      channel_ = 0;
      sourceId_ = 0;
      souceName_ = "";
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasChannel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSourceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSouceName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, channel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sourceId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSouceNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, channel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sourceId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSouceNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cg.base.io.proto.ChatProtos.RESPONSE_CHAT parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cg.base.io.proto.ChatProtos.RESPONSE_CHAT parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cg.base.io.proto.ChatProtos.RESPONSE_CHAT parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cg.base.io.proto.ChatProtos.RESPONSE_CHAT parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cg.base.io.proto.ChatProtos.RESPONSE_CHAT parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cg.base.io.proto.ChatProtos.RESPONSE_CHAT parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cg.base.io.proto.ChatProtos.RESPONSE_CHAT parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cg.base.io.proto.ChatProtos.RESPONSE_CHAT parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cg.base.io.proto.ChatProtos.RESPONSE_CHAT parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cg.base.io.proto.ChatProtos.RESPONSE_CHAT parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cg.base.io.proto.ChatProtos.RESPONSE_CHAT prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RESPONSE_CHAT}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cg.base.io.proto.ChatProtos.RESPONSE_CHATOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cg.base.io.proto.ChatProtos.internal_static_RESPONSE_CHAT_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cg.base.io.proto.ChatProtos.internal_static_RESPONSE_CHAT_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cg.base.io.proto.ChatProtos.RESPONSE_CHAT.class, cg.base.io.proto.ChatProtos.RESPONSE_CHAT.Builder.class);
      }

      // Construct using cg.base.io.proto.ChatProtos.RESPONSE_CHAT.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        channel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sourceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        souceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cg.base.io.proto.ChatProtos.internal_static_RESPONSE_CHAT_descriptor;
      }

      public cg.base.io.proto.ChatProtos.RESPONSE_CHAT getDefaultInstanceForType() {
        return cg.base.io.proto.ChatProtos.RESPONSE_CHAT.getDefaultInstance();
      }

      public cg.base.io.proto.ChatProtos.RESPONSE_CHAT build() {
        cg.base.io.proto.ChatProtos.RESPONSE_CHAT result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cg.base.io.proto.ChatProtos.RESPONSE_CHAT buildPartial() {
        cg.base.io.proto.ChatProtos.RESPONSE_CHAT result = new cg.base.io.proto.ChatProtos.RESPONSE_CHAT(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.channel_ = channel_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sourceId_ = sourceId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.souceName_ = souceName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cg.base.io.proto.ChatProtos.RESPONSE_CHAT) {
          return mergeFrom((cg.base.io.proto.ChatProtos.RESPONSE_CHAT)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cg.base.io.proto.ChatProtos.RESPONSE_CHAT other) {
        if (other == cg.base.io.proto.ChatProtos.RESPONSE_CHAT.getDefaultInstance()) return this;
        if (other.hasChannel()) {
          setChannel(other.getChannel());
        }
        if (other.hasSourceId()) {
          setSourceId(other.getSourceId());
        }
        if (other.hasSouceName()) {
          bitField0_ |= 0x00000004;
          souceName_ = other.souceName_;
          onChanged();
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000008;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasChannel()) {
          
          return false;
        }
        if (!hasSourceId()) {
          
          return false;
        }
        if (!hasSouceName()) {
          
          return false;
        }
        if (!hasText()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cg.base.io.proto.ChatProtos.RESPONSE_CHAT parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cg.base.io.proto.ChatProtos.RESPONSE_CHAT) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 channel = 1;
      private int channel_ ;
      /**
       * <code>required int32 channel = 1;</code>
       */
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 channel = 1;</code>
       */
      public int getChannel() {
        return channel_;
      }
      /**
       * <code>required int32 channel = 1;</code>
       */
      public Builder setChannel(int value) {
        bitField0_ |= 0x00000001;
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 channel = 1;</code>
       */
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        channel_ = 0;
        onChanged();
        return this;
      }

      // required int32 sourceId = 2;
      private int sourceId_ ;
      /**
       * <code>required int32 sourceId = 2;</code>
       */
      public boolean hasSourceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 sourceId = 2;</code>
       */
      public int getSourceId() {
        return sourceId_;
      }
      /**
       * <code>required int32 sourceId = 2;</code>
       */
      public Builder setSourceId(int value) {
        bitField0_ |= 0x00000002;
        sourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sourceId = 2;</code>
       */
      public Builder clearSourceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sourceId_ = 0;
        onChanged();
        return this;
      }

      // required string souceName = 3;
      private java.lang.Object souceName_ = "";
      /**
       * <code>required string souceName = 3;</code>
       */
      public boolean hasSouceName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string souceName = 3;</code>
       */
      public java.lang.String getSouceName() {
        java.lang.Object ref = souceName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          souceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string souceName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSouceNameBytes() {
        java.lang.Object ref = souceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          souceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string souceName = 3;</code>
       */
      public Builder setSouceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        souceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string souceName = 3;</code>
       */
      public Builder clearSouceName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        souceName_ = getDefaultInstance().getSouceName();
        onChanged();
        return this;
      }
      /**
       * <code>required string souceName = 3;</code>
       */
      public Builder setSouceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        souceName_ = value;
        onChanged();
        return this;
      }

      // required string text = 4;
      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 4;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string text = 4;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 4;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 4;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000008);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 4;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RESPONSE_CHAT)
    }

    static {
      defaultInstance = new RESPONSE_CHAT(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RESPONSE_CHAT)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_REQUEST_CHAT_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_REQUEST_CHAT_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RESPONSE_CHAT_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RESPONSE_CHAT_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nChat.proto\"?\n\014REQUEST_CHAT\022\017\n\007channel\030" +
      "\001 \002(\005\022\020\n\010targetId\030\002 \002(\005\022\014\n\004text\030\003 \002(\t\"R\n" +
      "\014RESPONSE_CHAT\022\017\n\007channel\030\001 \002(\005\022\020\n\010source" +
      "Id\030\002 \002(\005\022\021\n\tsouceName\030\003 \002(\t\022\014\n\004text\030\004 \002(" +
      "\tB\036\n\020cg.base.io.protoB\nChatProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_REQUEST_CHAT_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_REQUEST_CHAT_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_REQUEST_CHAT_descriptor,
              new java.lang.String[] { "Channel", "TargetId", "Text", });
          internal_static_RESPONSE_CHAT_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RESPONSE_CHAT_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RESPONSE_CHAT_descriptor,
              new java.lang.String[] { "Channel", "SourceId", "SouceName", "Text", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
