// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mail.proto

package cg.base.io.proto;

public final class MailProtos {
  private MailProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RESPONSE_MAIL_SENDOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 type = 1;
    boolean hasType();
    int getType();
    
    // required int32 status = 2;
    boolean hasStatus();
    int getStatus();
    
    // required int32 sourceId = 3;
    boolean hasSourceId();
    int getSourceId();
    
    // required int32 destId = 4;
    boolean hasDestId();
    int getDestId();
    
    // required int32 lastTime = 5;
    boolean hasLastTime();
    int getLastTime();
    
    // required string sourceName = 6;
    boolean hasSourceName();
    String getSourceName();
    
    // required string title = 7;
    boolean hasTitle();
    String getTitle();
    
    // required string content = 8;
    boolean hasContent();
    String getContent();
    
    // repeated .VO_ATTACHMENT attachments = 9;
    java.util.List<cg.base.io.proto.VOProtos.VO_ATTACHMENT> 
        getAttachmentsList();
    cg.base.io.proto.VOProtos.VO_ATTACHMENT getAttachments(int index);
    int getAttachmentsCount();
    java.util.List<? extends cg.base.io.proto.VOProtos.VO_ATTACHMENTOrBuilder> 
        getAttachmentsOrBuilderList();
    cg.base.io.proto.VOProtos.VO_ATTACHMENTOrBuilder getAttachmentsOrBuilder(
        int index);
    
    // repeated .VO_PRICE prices = 10;
    java.util.List<cg.base.io.proto.VOProtos.VO_PRICE> 
        getPricesList();
    cg.base.io.proto.VOProtos.VO_PRICE getPrices(int index);
    int getPricesCount();
    java.util.List<? extends cg.base.io.proto.VOProtos.VO_PRICEOrBuilder> 
        getPricesOrBuilderList();
    cg.base.io.proto.VOProtos.VO_PRICEOrBuilder getPricesOrBuilder(
        int index);
  }
  public static final class RESPONSE_MAIL_SEND extends
      com.google.protobuf.GeneratedMessage
      implements RESPONSE_MAIL_SENDOrBuilder {
    // Use RESPONSE_MAIL_SEND.newBuilder() to construct.
    private RESPONSE_MAIL_SEND(Builder builder) {
      super(builder);
    }
    private RESPONSE_MAIL_SEND(boolean noInit) {}
    
    private static final RESPONSE_MAIL_SEND defaultInstance;
    public static RESPONSE_MAIL_SEND getDefaultInstance() {
      return defaultInstance;
    }
    
    public RESPONSE_MAIL_SEND getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cg.base.io.proto.MailProtos.internal_static_RESPONSE_MAIL_SEND_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cg.base.io.proto.MailProtos.internal_static_RESPONSE_MAIL_SEND_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getType() {
      return type_;
    }
    
    // required int32 status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getStatus() {
      return status_;
    }
    
    // required int32 sourceId = 3;
    public static final int SOURCEID_FIELD_NUMBER = 3;
    private int sourceId_;
    public boolean hasSourceId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getSourceId() {
      return sourceId_;
    }
    
    // required int32 destId = 4;
    public static final int DESTID_FIELD_NUMBER = 4;
    private int destId_;
    public boolean hasDestId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getDestId() {
      return destId_;
    }
    
    // required int32 lastTime = 5;
    public static final int LASTTIME_FIELD_NUMBER = 5;
    private int lastTime_;
    public boolean hasLastTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getLastTime() {
      return lastTime_;
    }
    
    // required string sourceName = 6;
    public static final int SOURCENAME_FIELD_NUMBER = 6;
    private java.lang.Object sourceName_;
    public boolean hasSourceName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getSourceName() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sourceName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSourceNameBytes() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sourceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string title = 7;
    public static final int TITLE_FIELD_NUMBER = 7;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string content = 8;
    public static final int CONTENT_FIELD_NUMBER = 8;
    private java.lang.Object content_;
    public boolean hasContent() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          content_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .VO_ATTACHMENT attachments = 9;
    public static final int ATTACHMENTS_FIELD_NUMBER = 9;
    private java.util.List<cg.base.io.proto.VOProtos.VO_ATTACHMENT> attachments_;
    public java.util.List<cg.base.io.proto.VOProtos.VO_ATTACHMENT> getAttachmentsList() {
      return attachments_;
    }
    public java.util.List<? extends cg.base.io.proto.VOProtos.VO_ATTACHMENTOrBuilder> 
        getAttachmentsOrBuilderList() {
      return attachments_;
    }
    public int getAttachmentsCount() {
      return attachments_.size();
    }
    public cg.base.io.proto.VOProtos.VO_ATTACHMENT getAttachments(int index) {
      return attachments_.get(index);
    }
    public cg.base.io.proto.VOProtos.VO_ATTACHMENTOrBuilder getAttachmentsOrBuilder(
        int index) {
      return attachments_.get(index);
    }
    
    // repeated .VO_PRICE prices = 10;
    public static final int PRICES_FIELD_NUMBER = 10;
    private java.util.List<cg.base.io.proto.VOProtos.VO_PRICE> prices_;
    public java.util.List<cg.base.io.proto.VOProtos.VO_PRICE> getPricesList() {
      return prices_;
    }
    public java.util.List<? extends cg.base.io.proto.VOProtos.VO_PRICEOrBuilder> 
        getPricesOrBuilderList() {
      return prices_;
    }
    public int getPricesCount() {
      return prices_.size();
    }
    public cg.base.io.proto.VOProtos.VO_PRICE getPrices(int index) {
      return prices_.get(index);
    }
    public cg.base.io.proto.VOProtos.VO_PRICEOrBuilder getPricesOrBuilder(
        int index) {
      return prices_.get(index);
    }
    
    private void initFields() {
      type_ = 0;
      status_ = 0;
      sourceId_ = 0;
      destId_ = 0;
      lastTime_ = 0;
      sourceName_ = "";
      title_ = "";
      content_ = "";
      attachments_ = java.util.Collections.emptyList();
      prices_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSourceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSourceName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAttachmentsCount(); i++) {
        if (!getAttachments(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getPricesCount(); i++) {
        if (!getPrices(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, sourceId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, destId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, lastTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getSourceNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getTitleBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getContentBytes());
      }
      for (int i = 0; i < attachments_.size(); i++) {
        output.writeMessage(9, attachments_.get(i));
      }
      for (int i = 0; i < prices_.size(); i++) {
        output.writeMessage(10, prices_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sourceId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, destId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, lastTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getSourceNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTitleBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getContentBytes());
      }
      for (int i = 0; i < attachments_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, attachments_.get(i));
      }
      for (int i = 0; i < prices_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, prices_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cg.base.io.proto.MailProtos.RESPONSE_MAIL_SENDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cg.base.io.proto.MailProtos.internal_static_RESPONSE_MAIL_SEND_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cg.base.io.proto.MailProtos.internal_static_RESPONSE_MAIL_SEND_fieldAccessorTable;
      }
      
      // Construct using cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttachmentsFieldBuilder();
          getPricesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        sourceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        destId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        lastTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        sourceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        if (attachmentsBuilder_ == null) {
          attachments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          attachmentsBuilder_.clear();
        }
        if (pricesBuilder_ == null) {
          prices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          pricesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND.getDescriptor();
      }
      
      public cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND getDefaultInstanceForType() {
        return cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND.getDefaultInstance();
      }
      
      public cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND build() {
        cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND buildPartial() {
        cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND result = new cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sourceId_ = sourceId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.destId_ = destId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.lastTime_ = lastTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sourceName_ = sourceName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.content_ = content_;
        if (attachmentsBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            attachments_ = java.util.Collections.unmodifiableList(attachments_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.attachments_ = attachments_;
        } else {
          result.attachments_ = attachmentsBuilder_.build();
        }
        if (pricesBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200)) {
            prices_ = java.util.Collections.unmodifiableList(prices_);
            bitField0_ = (bitField0_ & ~0x00000200);
          }
          result.prices_ = prices_;
        } else {
          result.prices_ = pricesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND) {
          return mergeFrom((cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND other) {
        if (other == cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasSourceId()) {
          setSourceId(other.getSourceId());
        }
        if (other.hasDestId()) {
          setDestId(other.getDestId());
        }
        if (other.hasLastTime()) {
          setLastTime(other.getLastTime());
        }
        if (other.hasSourceName()) {
          setSourceName(other.getSourceName());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (attachmentsBuilder_ == null) {
          if (!other.attachments_.isEmpty()) {
            if (attachments_.isEmpty()) {
              attachments_ = other.attachments_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureAttachmentsIsMutable();
              attachments_.addAll(other.attachments_);
            }
            onChanged();
          }
        } else {
          if (!other.attachments_.isEmpty()) {
            if (attachmentsBuilder_.isEmpty()) {
              attachmentsBuilder_.dispose();
              attachmentsBuilder_ = null;
              attachments_ = other.attachments_;
              bitField0_ = (bitField0_ & ~0x00000100);
              attachmentsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttachmentsFieldBuilder() : null;
            } else {
              attachmentsBuilder_.addAllMessages(other.attachments_);
            }
          }
        }
        if (pricesBuilder_ == null) {
          if (!other.prices_.isEmpty()) {
            if (prices_.isEmpty()) {
              prices_ = other.prices_;
              bitField0_ = (bitField0_ & ~0x00000200);
            } else {
              ensurePricesIsMutable();
              prices_.addAll(other.prices_);
            }
            onChanged();
          }
        } else {
          if (!other.prices_.isEmpty()) {
            if (pricesBuilder_.isEmpty()) {
              pricesBuilder_.dispose();
              pricesBuilder_ = null;
              prices_ = other.prices_;
              bitField0_ = (bitField0_ & ~0x00000200);
              pricesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPricesFieldBuilder() : null;
            } else {
              pricesBuilder_.addAllMessages(other.prices_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        if (!hasSourceId()) {
          
          return false;
        }
        if (!hasDestId()) {
          
          return false;
        }
        if (!hasLastTime()) {
          
          return false;
        }
        if (!hasSourceName()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        for (int i = 0; i < getAttachmentsCount(); i++) {
          if (!getAttachments(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getPricesCount(); i++) {
          if (!getPrices(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              status_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sourceId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              destId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              lastTime_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              sourceName_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              title_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              content_ = input.readBytes();
              break;
            }
            case 74: {
              cg.base.io.proto.VOProtos.VO_ATTACHMENT.Builder subBuilder = cg.base.io.proto.VOProtos.VO_ATTACHMENT.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAttachments(subBuilder.buildPartial());
              break;
            }
            case 82: {
              cg.base.io.proto.VOProtos.VO_PRICE.Builder subBuilder = cg.base.io.proto.VOProtos.VO_PRICE.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPrices(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 type = 1;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 status = 2;
      private int status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getStatus() {
        return status_;
      }
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 sourceId = 3;
      private int sourceId_ ;
      public boolean hasSourceId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getSourceId() {
        return sourceId_;
      }
      public Builder setSourceId(int value) {
        bitField0_ |= 0x00000004;
        sourceId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSourceId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sourceId_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 destId = 4;
      private int destId_ ;
      public boolean hasDestId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getDestId() {
        return destId_;
      }
      public Builder setDestId(int value) {
        bitField0_ |= 0x00000008;
        destId_ = value;
        onChanged();
        return this;
      }
      public Builder clearDestId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        destId_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 lastTime = 5;
      private int lastTime_ ;
      public boolean hasLastTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getLastTime() {
        return lastTime_;
      }
      public Builder setLastTime(int value) {
        bitField0_ |= 0x00000010;
        lastTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lastTime_ = 0;
        onChanged();
        return this;
      }
      
      // required string sourceName = 6;
      private java.lang.Object sourceName_ = "";
      public boolean hasSourceName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getSourceName() {
        java.lang.Object ref = sourceName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sourceName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSourceName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        sourceName_ = value;
        onChanged();
        return this;
      }
      public Builder clearSourceName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sourceName_ = getDefaultInstance().getSourceName();
        onChanged();
        return this;
      }
      void setSourceName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        sourceName_ = value;
        onChanged();
      }
      
      // required string title = 7;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000040);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        title_ = value;
        onChanged();
      }
      
      // required string content = 8;
      private java.lang.Object content_ = "";
      public boolean hasContent() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContent(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        content_ = value;
        onChanged();
        return this;
      }
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000080);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      void setContent(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        content_ = value;
        onChanged();
      }
      
      // repeated .VO_ATTACHMENT attachments = 9;
      private java.util.List<cg.base.io.proto.VOProtos.VO_ATTACHMENT> attachments_ =
        java.util.Collections.emptyList();
      private void ensureAttachmentsIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          attachments_ = new java.util.ArrayList<cg.base.io.proto.VOProtos.VO_ATTACHMENT>(attachments_);
          bitField0_ |= 0x00000100;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          cg.base.io.proto.VOProtos.VO_ATTACHMENT, cg.base.io.proto.VOProtos.VO_ATTACHMENT.Builder, cg.base.io.proto.VOProtos.VO_ATTACHMENTOrBuilder> attachmentsBuilder_;
      
      public java.util.List<cg.base.io.proto.VOProtos.VO_ATTACHMENT> getAttachmentsList() {
        if (attachmentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attachments_);
        } else {
          return attachmentsBuilder_.getMessageList();
        }
      }
      public int getAttachmentsCount() {
        if (attachmentsBuilder_ == null) {
          return attachments_.size();
        } else {
          return attachmentsBuilder_.getCount();
        }
      }
      public cg.base.io.proto.VOProtos.VO_ATTACHMENT getAttachments(int index) {
        if (attachmentsBuilder_ == null) {
          return attachments_.get(index);
        } else {
          return attachmentsBuilder_.getMessage(index);
        }
      }
      public Builder setAttachments(
          int index, cg.base.io.proto.VOProtos.VO_ATTACHMENT value) {
        if (attachmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttachmentsIsMutable();
          attachments_.set(index, value);
          onChanged();
        } else {
          attachmentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAttachments(
          int index, cg.base.io.proto.VOProtos.VO_ATTACHMENT.Builder builderForValue) {
        if (attachmentsBuilder_ == null) {
          ensureAttachmentsIsMutable();
          attachments_.set(index, builderForValue.build());
          onChanged();
        } else {
          attachmentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAttachments(cg.base.io.proto.VOProtos.VO_ATTACHMENT value) {
        if (attachmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttachmentsIsMutable();
          attachments_.add(value);
          onChanged();
        } else {
          attachmentsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAttachments(
          int index, cg.base.io.proto.VOProtos.VO_ATTACHMENT value) {
        if (attachmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttachmentsIsMutable();
          attachments_.add(index, value);
          onChanged();
        } else {
          attachmentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAttachments(
          cg.base.io.proto.VOProtos.VO_ATTACHMENT.Builder builderForValue) {
        if (attachmentsBuilder_ == null) {
          ensureAttachmentsIsMutable();
          attachments_.add(builderForValue.build());
          onChanged();
        } else {
          attachmentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAttachments(
          int index, cg.base.io.proto.VOProtos.VO_ATTACHMENT.Builder builderForValue) {
        if (attachmentsBuilder_ == null) {
          ensureAttachmentsIsMutable();
          attachments_.add(index, builderForValue.build());
          onChanged();
        } else {
          attachmentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAttachments(
          java.lang.Iterable<? extends cg.base.io.proto.VOProtos.VO_ATTACHMENT> values) {
        if (attachmentsBuilder_ == null) {
          ensureAttachmentsIsMutable();
          super.addAll(values, attachments_);
          onChanged();
        } else {
          attachmentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAttachments() {
        if (attachmentsBuilder_ == null) {
          attachments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          attachmentsBuilder_.clear();
        }
        return this;
      }
      public Builder removeAttachments(int index) {
        if (attachmentsBuilder_ == null) {
          ensureAttachmentsIsMutable();
          attachments_.remove(index);
          onChanged();
        } else {
          attachmentsBuilder_.remove(index);
        }
        return this;
      }
      public cg.base.io.proto.VOProtos.VO_ATTACHMENT.Builder getAttachmentsBuilder(
          int index) {
        return getAttachmentsFieldBuilder().getBuilder(index);
      }
      public cg.base.io.proto.VOProtos.VO_ATTACHMENTOrBuilder getAttachmentsOrBuilder(
          int index) {
        if (attachmentsBuilder_ == null) {
          return attachments_.get(index);  } else {
          return attachmentsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends cg.base.io.proto.VOProtos.VO_ATTACHMENTOrBuilder> 
           getAttachmentsOrBuilderList() {
        if (attachmentsBuilder_ != null) {
          return attachmentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attachments_);
        }
      }
      public cg.base.io.proto.VOProtos.VO_ATTACHMENT.Builder addAttachmentsBuilder() {
        return getAttachmentsFieldBuilder().addBuilder(
            cg.base.io.proto.VOProtos.VO_ATTACHMENT.getDefaultInstance());
      }
      public cg.base.io.proto.VOProtos.VO_ATTACHMENT.Builder addAttachmentsBuilder(
          int index) {
        return getAttachmentsFieldBuilder().addBuilder(
            index, cg.base.io.proto.VOProtos.VO_ATTACHMENT.getDefaultInstance());
      }
      public java.util.List<cg.base.io.proto.VOProtos.VO_ATTACHMENT.Builder> 
           getAttachmentsBuilderList() {
        return getAttachmentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cg.base.io.proto.VOProtos.VO_ATTACHMENT, cg.base.io.proto.VOProtos.VO_ATTACHMENT.Builder, cg.base.io.proto.VOProtos.VO_ATTACHMENTOrBuilder> 
          getAttachmentsFieldBuilder() {
        if (attachmentsBuilder_ == null) {
          attachmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cg.base.io.proto.VOProtos.VO_ATTACHMENT, cg.base.io.proto.VOProtos.VO_ATTACHMENT.Builder, cg.base.io.proto.VOProtos.VO_ATTACHMENTOrBuilder>(
                  attachments_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          attachments_ = null;
        }
        return attachmentsBuilder_;
      }
      
      // repeated .VO_PRICE prices = 10;
      private java.util.List<cg.base.io.proto.VOProtos.VO_PRICE> prices_ =
        java.util.Collections.emptyList();
      private void ensurePricesIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          prices_ = new java.util.ArrayList<cg.base.io.proto.VOProtos.VO_PRICE>(prices_);
          bitField0_ |= 0x00000200;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          cg.base.io.proto.VOProtos.VO_PRICE, cg.base.io.proto.VOProtos.VO_PRICE.Builder, cg.base.io.proto.VOProtos.VO_PRICEOrBuilder> pricesBuilder_;
      
      public java.util.List<cg.base.io.proto.VOProtos.VO_PRICE> getPricesList() {
        if (pricesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(prices_);
        } else {
          return pricesBuilder_.getMessageList();
        }
      }
      public int getPricesCount() {
        if (pricesBuilder_ == null) {
          return prices_.size();
        } else {
          return pricesBuilder_.getCount();
        }
      }
      public cg.base.io.proto.VOProtos.VO_PRICE getPrices(int index) {
        if (pricesBuilder_ == null) {
          return prices_.get(index);
        } else {
          return pricesBuilder_.getMessage(index);
        }
      }
      public Builder setPrices(
          int index, cg.base.io.proto.VOProtos.VO_PRICE value) {
        if (pricesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePricesIsMutable();
          prices_.set(index, value);
          onChanged();
        } else {
          pricesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPrices(
          int index, cg.base.io.proto.VOProtos.VO_PRICE.Builder builderForValue) {
        if (pricesBuilder_ == null) {
          ensurePricesIsMutable();
          prices_.set(index, builderForValue.build());
          onChanged();
        } else {
          pricesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPrices(cg.base.io.proto.VOProtos.VO_PRICE value) {
        if (pricesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePricesIsMutable();
          prices_.add(value);
          onChanged();
        } else {
          pricesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPrices(
          int index, cg.base.io.proto.VOProtos.VO_PRICE value) {
        if (pricesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePricesIsMutable();
          prices_.add(index, value);
          onChanged();
        } else {
          pricesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPrices(
          cg.base.io.proto.VOProtos.VO_PRICE.Builder builderForValue) {
        if (pricesBuilder_ == null) {
          ensurePricesIsMutable();
          prices_.add(builderForValue.build());
          onChanged();
        } else {
          pricesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPrices(
          int index, cg.base.io.proto.VOProtos.VO_PRICE.Builder builderForValue) {
        if (pricesBuilder_ == null) {
          ensurePricesIsMutable();
          prices_.add(index, builderForValue.build());
          onChanged();
        } else {
          pricesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPrices(
          java.lang.Iterable<? extends cg.base.io.proto.VOProtos.VO_PRICE> values) {
        if (pricesBuilder_ == null) {
          ensurePricesIsMutable();
          super.addAll(values, prices_);
          onChanged();
        } else {
          pricesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPrices() {
        if (pricesBuilder_ == null) {
          prices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
          onChanged();
        } else {
          pricesBuilder_.clear();
        }
        return this;
      }
      public Builder removePrices(int index) {
        if (pricesBuilder_ == null) {
          ensurePricesIsMutable();
          prices_.remove(index);
          onChanged();
        } else {
          pricesBuilder_.remove(index);
        }
        return this;
      }
      public cg.base.io.proto.VOProtos.VO_PRICE.Builder getPricesBuilder(
          int index) {
        return getPricesFieldBuilder().getBuilder(index);
      }
      public cg.base.io.proto.VOProtos.VO_PRICEOrBuilder getPricesOrBuilder(
          int index) {
        if (pricesBuilder_ == null) {
          return prices_.get(index);  } else {
          return pricesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends cg.base.io.proto.VOProtos.VO_PRICEOrBuilder> 
           getPricesOrBuilderList() {
        if (pricesBuilder_ != null) {
          return pricesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(prices_);
        }
      }
      public cg.base.io.proto.VOProtos.VO_PRICE.Builder addPricesBuilder() {
        return getPricesFieldBuilder().addBuilder(
            cg.base.io.proto.VOProtos.VO_PRICE.getDefaultInstance());
      }
      public cg.base.io.proto.VOProtos.VO_PRICE.Builder addPricesBuilder(
          int index) {
        return getPricesFieldBuilder().addBuilder(
            index, cg.base.io.proto.VOProtos.VO_PRICE.getDefaultInstance());
      }
      public java.util.List<cg.base.io.proto.VOProtos.VO_PRICE.Builder> 
           getPricesBuilderList() {
        return getPricesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cg.base.io.proto.VOProtos.VO_PRICE, cg.base.io.proto.VOProtos.VO_PRICE.Builder, cg.base.io.proto.VOProtos.VO_PRICEOrBuilder> 
          getPricesFieldBuilder() {
        if (pricesBuilder_ == null) {
          pricesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cg.base.io.proto.VOProtos.VO_PRICE, cg.base.io.proto.VOProtos.VO_PRICE.Builder, cg.base.io.proto.VOProtos.VO_PRICEOrBuilder>(
                  prices_,
                  ((bitField0_ & 0x00000200) == 0x00000200),
                  getParentForChildren(),
                  isClean());
          prices_ = null;
        }
        return pricesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:RESPONSE_MAIL_SEND)
    }
    
    static {
      defaultInstance = new RESPONSE_MAIL_SEND(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RESPONSE_MAIL_SEND)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RESPONSE_MAIL_SEND_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RESPONSE_MAIL_SEND_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nMail.proto\032\010VO.proto\"\332\001\n\022RESPONSE_MAIL" +
      "_SEND\022\014\n\004type\030\001 \002(\005\022\016\n\006status\030\002 \002(\005\022\020\n\010s" +
      "ourceId\030\003 \002(\005\022\016\n\006destId\030\004 \002(\005\022\020\n\010lastTim" +
      "e\030\005 \002(\005\022\022\n\nsourceName\030\006 \002(\t\022\r\n\005title\030\007 \002" +
      "(\t\022\017\n\007content\030\010 \002(\t\022#\n\013attachments\030\t \003(\013" +
      "2\016.VO_ATTACHMENT\022\031\n\006prices\030\n \003(\0132\t.VO_PR" +
      "ICEB\036\n\020cg.base.io.protoB\nMailProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RESPONSE_MAIL_SEND_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RESPONSE_MAIL_SEND_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RESPONSE_MAIL_SEND_descriptor,
              new java.lang.String[] { "Type", "Status", "SourceId", "DestId", "LastTime", "SourceName", "Title", "Content", "Attachments", "Prices", },
              cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND.class,
              cg.base.io.proto.MailProtos.RESPONSE_MAIL_SEND.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cg.base.io.proto.VOProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
