// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Script.proto

package cg.base.io.proto;

public final class ScriptProtos {
  private ScriptProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface REQUEST_SCRIPT_MUTUALOrBuilder extends
      // @@protoc_insertion_point(interface_extends:REQUEST_SCRIPT_MUTUAL)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 dir = 1;</code>
     */
    boolean hasDir();
    /**
     * <code>required int32 dir = 1;</code>
     */
    int getDir();

    /**
     * <code>optional int32 op = 2 [default = 0];</code>
     */
    boolean hasOp();
    /**
     * <code>optional int32 op = 2 [default = 0];</code>
     */
    int getOp();

    /**
     * <code>optional string message = 3;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code REQUEST_SCRIPT_MUTUAL}
   */
  public static final class REQUEST_SCRIPT_MUTUAL extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:REQUEST_SCRIPT_MUTUAL)
      REQUEST_SCRIPT_MUTUALOrBuilder {
    // Use REQUEST_SCRIPT_MUTUAL.newBuilder() to construct.
    private REQUEST_SCRIPT_MUTUAL(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private REQUEST_SCRIPT_MUTUAL(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final REQUEST_SCRIPT_MUTUAL defaultInstance;
    public static REQUEST_SCRIPT_MUTUAL getDefaultInstance() {
      return defaultInstance;
    }

    public REQUEST_SCRIPT_MUTUAL getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private REQUEST_SCRIPT_MUTUAL(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              dir_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              op_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              message_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cg.base.io.proto.ScriptProtos.internal_static_REQUEST_SCRIPT_MUTUAL_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cg.base.io.proto.ScriptProtos.internal_static_REQUEST_SCRIPT_MUTUAL_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL.class, cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL.Builder.class);
    }

    public static com.google.protobuf.Parser<REQUEST_SCRIPT_MUTUAL> PARSER =
        new com.google.protobuf.AbstractParser<REQUEST_SCRIPT_MUTUAL>() {
      public REQUEST_SCRIPT_MUTUAL parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new REQUEST_SCRIPT_MUTUAL(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<REQUEST_SCRIPT_MUTUAL> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DIR_FIELD_NUMBER = 1;
    private int dir_;
    /**
     * <code>required int32 dir = 1;</code>
     */
    public boolean hasDir() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 dir = 1;</code>
     */
    public int getDir() {
      return dir_;
    }

    public static final int OP_FIELD_NUMBER = 2;
    private int op_;
    /**
     * <code>optional int32 op = 2 [default = 0];</code>
     */
    public boolean hasOp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 op = 2 [default = 0];</code>
     */
    public int getOp() {
      return op_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 3;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      dir_ = 0;
      op_ = 0;
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDir()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, dir_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, op_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, dir_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, op_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code REQUEST_SCRIPT_MUTUAL}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:REQUEST_SCRIPT_MUTUAL)
        cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUALOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cg.base.io.proto.ScriptProtos.internal_static_REQUEST_SCRIPT_MUTUAL_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cg.base.io.proto.ScriptProtos.internal_static_REQUEST_SCRIPT_MUTUAL_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL.class, cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL.Builder.class);
      }

      // Construct using cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        dir_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        op_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cg.base.io.proto.ScriptProtos.internal_static_REQUEST_SCRIPT_MUTUAL_descriptor;
      }

      public cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL getDefaultInstanceForType() {
        return cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL.getDefaultInstance();
      }

      public cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL build() {
        cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL buildPartial() {
        cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL result = new cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dir_ = dir_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.op_ = op_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL) {
          return mergeFrom((cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL other) {
        if (other == cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL.getDefaultInstance()) return this;
        if (other.hasDir()) {
          setDir(other.getDir());
        }
        if (other.hasOp()) {
          setOp(other.getOp());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000004;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDir()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cg.base.io.proto.ScriptProtos.REQUEST_SCRIPT_MUTUAL) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int dir_ ;
      /**
       * <code>required int32 dir = 1;</code>
       */
      public boolean hasDir() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 dir = 1;</code>
       */
      public int getDir() {
        return dir_;
      }
      /**
       * <code>required int32 dir = 1;</code>
       */
      public Builder setDir(int value) {
        bitField0_ |= 0x00000001;
        dir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 dir = 1;</code>
       */
      public Builder clearDir() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dir_ = 0;
        onChanged();
        return this;
      }

      private int op_ ;
      /**
       * <code>optional int32 op = 2 [default = 0];</code>
       */
      public boolean hasOp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 op = 2 [default = 0];</code>
       */
      public int getOp() {
        return op_;
      }
      /**
       * <code>optional int32 op = 2 [default = 0];</code>
       */
      public Builder setOp(int value) {
        bitField0_ |= 0x00000002;
        op_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 op = 2 [default = 0];</code>
       */
      public Builder clearOp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        op_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 3;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:REQUEST_SCRIPT_MUTUAL)
    }

    static {
      defaultInstance = new REQUEST_SCRIPT_MUTUAL(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:REQUEST_SCRIPT_MUTUAL)
  }

  public interface RESPONSE_SCRIPTOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RESPONSE_SCRIPT)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string talkType = 1;</code>
     */
    boolean hasTalkType();
    /**
     * <code>required string talkType = 1;</code>
     */
    java.lang.String getTalkType();
    /**
     * <code>required string talkType = 1;</code>
     */
    com.google.protobuf.ByteString
        getTalkTypeBytes();

    /**
     * <code>required string message = 2;</code>
     */
    boolean hasMessage();
    /**
     * <code>required string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>required string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>repeated string infos = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getInfosList();
    /**
     * <code>repeated string infos = 3;</code>
     */
    int getInfosCount();
    /**
     * <code>repeated string infos = 3;</code>
     */
    java.lang.String getInfos(int index);
    /**
     * <code>repeated string infos = 3;</code>
     */
    com.google.protobuf.ByteString
        getInfosBytes(int index);
  }
  /**
   * Protobuf type {@code RESPONSE_SCRIPT}
   */
  public static final class RESPONSE_SCRIPT extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RESPONSE_SCRIPT)
      RESPONSE_SCRIPTOrBuilder {
    // Use RESPONSE_SCRIPT.newBuilder() to construct.
    private RESPONSE_SCRIPT(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RESPONSE_SCRIPT(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RESPONSE_SCRIPT defaultInstance;
    public static RESPONSE_SCRIPT getDefaultInstance() {
      return defaultInstance;
    }

    public RESPONSE_SCRIPT getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RESPONSE_SCRIPT(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              talkType_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              message_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                infos_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              infos_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          infos_ = infos_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cg.base.io.proto.ScriptProtos.internal_static_RESPONSE_SCRIPT_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cg.base.io.proto.ScriptProtos.internal_static_RESPONSE_SCRIPT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT.class, cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT.Builder.class);
    }

    public static com.google.protobuf.Parser<RESPONSE_SCRIPT> PARSER =
        new com.google.protobuf.AbstractParser<RESPONSE_SCRIPT>() {
      public RESPONSE_SCRIPT parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RESPONSE_SCRIPT(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RESPONSE_SCRIPT> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TALKTYPE_FIELD_NUMBER = 1;
    private java.lang.Object talkType_;
    /**
     * <code>required string talkType = 1;</code>
     */
    public boolean hasTalkType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string talkType = 1;</code>
     */
    public java.lang.String getTalkType() {
      java.lang.Object ref = talkType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          talkType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string talkType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTalkTypeBytes() {
      java.lang.Object ref = talkType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        talkType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object message_;
    /**
     * <code>required string message = 2;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INFOS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList infos_;
    /**
     * <code>repeated string infos = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInfosList() {
      return infos_;
    }
    /**
     * <code>repeated string infos = 3;</code>
     */
    public int getInfosCount() {
      return infos_.size();
    }
    /**
     * <code>repeated string infos = 3;</code>
     */
    public java.lang.String getInfos(int index) {
      return infos_.get(index);
    }
    /**
     * <code>repeated string infos = 3;</code>
     */
    public com.google.protobuf.ByteString
        getInfosBytes(int index) {
      return infos_.getByteString(index);
    }

    private void initFields() {
      talkType_ = "";
      message_ = "";
      infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTalkType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTalkTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMessageBytes());
      }
      for (int i = 0; i < infos_.size(); i++) {
        output.writeBytes(3, infos_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTalkTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < infos_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(infos_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getInfosList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RESPONSE_SCRIPT}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RESPONSE_SCRIPT)
        cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPTOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cg.base.io.proto.ScriptProtos.internal_static_RESPONSE_SCRIPT_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cg.base.io.proto.ScriptProtos.internal_static_RESPONSE_SCRIPT_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT.class, cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT.Builder.class);
      }

      // Construct using cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        talkType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cg.base.io.proto.ScriptProtos.internal_static_RESPONSE_SCRIPT_descriptor;
      }

      public cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT getDefaultInstanceForType() {
        return cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT.getDefaultInstance();
      }

      public cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT build() {
        cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT buildPartial() {
        cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT result = new cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.talkType_ = talkType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          infos_ = infos_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.infos_ = infos_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT) {
          return mergeFrom((cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT other) {
        if (other == cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT.getDefaultInstance()) return this;
        if (other.hasTalkType()) {
          bitField0_ |= 0x00000001;
          talkType_ = other.talkType_;
          onChanged();
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000002;
          message_ = other.message_;
          onChanged();
        }
        if (!other.infos_.isEmpty()) {
          if (infos_.isEmpty()) {
            infos_ = other.infos_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureInfosIsMutable();
            infos_.addAll(other.infos_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTalkType()) {
          
          return false;
        }
        if (!hasMessage()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object talkType_ = "";
      /**
       * <code>required string talkType = 1;</code>
       */
      public boolean hasTalkType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string talkType = 1;</code>
       */
      public java.lang.String getTalkType() {
        java.lang.Object ref = talkType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            talkType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string talkType = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTalkTypeBytes() {
        java.lang.Object ref = talkType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          talkType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string talkType = 1;</code>
       */
      public Builder setTalkType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        talkType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string talkType = 1;</code>
       */
      public Builder clearTalkType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        talkType_ = getDefaultInstance().getTalkType();
        onChanged();
        return this;
      }
      /**
       * <code>required string talkType = 1;</code>
       */
      public Builder setTalkTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        talkType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>required string message = 2;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 2;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInfosIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          infos_ = new com.google.protobuf.LazyStringArrayList(infos_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string infos = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getInfosList() {
        return infos_.getUnmodifiableView();
      }
      /**
       * <code>repeated string infos = 3;</code>
       */
      public int getInfosCount() {
        return infos_.size();
      }
      /**
       * <code>repeated string infos = 3;</code>
       */
      public java.lang.String getInfos(int index) {
        return infos_.get(index);
      }
      /**
       * <code>repeated string infos = 3;</code>
       */
      public com.google.protobuf.ByteString
          getInfosBytes(int index) {
        return infos_.getByteString(index);
      }
      /**
       * <code>repeated string infos = 3;</code>
       */
      public Builder setInfos(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfosIsMutable();
        infos_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 3;</code>
       */
      public Builder addInfos(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfosIsMutable();
        infos_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 3;</code>
       */
      public Builder addAllInfos(
          java.lang.Iterable<java.lang.String> values) {
        ensureInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, infos_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 3;</code>
       */
      public Builder clearInfos() {
        infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 3;</code>
       */
      public Builder addInfosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfosIsMutable();
        infos_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RESPONSE_SCRIPT)
    }

    static {
      defaultInstance = new RESPONSE_SCRIPT(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RESPONSE_SCRIPT)
  }

  public interface RESPONSE_SCRIPT_ERROROrBuilder extends
      // @@protoc_insertion_point(interface_extends:RESPONSE_SCRIPT_ERROR)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string talkType = 1;</code>
     */
    boolean hasTalkType();
    /**
     * <code>required string talkType = 1;</code>
     */
    java.lang.String getTalkType();
    /**
     * <code>required string talkType = 1;</code>
     */
    com.google.protobuf.ByteString
        getTalkTypeBytes();

    /**
     * <code>required int32 message = 2;</code>
     */
    boolean hasMessage();
    /**
     * <code>required int32 message = 2;</code>
     */
    int getMessage();
  }
  /**
   * Protobuf type {@code RESPONSE_SCRIPT_ERROR}
   */
  public static final class RESPONSE_SCRIPT_ERROR extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RESPONSE_SCRIPT_ERROR)
      RESPONSE_SCRIPT_ERROROrBuilder {
    // Use RESPONSE_SCRIPT_ERROR.newBuilder() to construct.
    private RESPONSE_SCRIPT_ERROR(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RESPONSE_SCRIPT_ERROR(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RESPONSE_SCRIPT_ERROR defaultInstance;
    public static RESPONSE_SCRIPT_ERROR getDefaultInstance() {
      return defaultInstance;
    }

    public RESPONSE_SCRIPT_ERROR getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RESPONSE_SCRIPT_ERROR(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              talkType_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              message_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cg.base.io.proto.ScriptProtos.internal_static_RESPONSE_SCRIPT_ERROR_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cg.base.io.proto.ScriptProtos.internal_static_RESPONSE_SCRIPT_ERROR_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR.class, cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR.Builder.class);
    }

    public static com.google.protobuf.Parser<RESPONSE_SCRIPT_ERROR> PARSER =
        new com.google.protobuf.AbstractParser<RESPONSE_SCRIPT_ERROR>() {
      public RESPONSE_SCRIPT_ERROR parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RESPONSE_SCRIPT_ERROR(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RESPONSE_SCRIPT_ERROR> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TALKTYPE_FIELD_NUMBER = 1;
    private java.lang.Object talkType_;
    /**
     * <code>required string talkType = 1;</code>
     */
    public boolean hasTalkType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string talkType = 1;</code>
     */
    public java.lang.String getTalkType() {
      java.lang.Object ref = talkType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          talkType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string talkType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTalkTypeBytes() {
      java.lang.Object ref = talkType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        talkType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private int message_;
    /**
     * <code>required int32 message = 2;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 message = 2;</code>
     */
    public int getMessage() {
      return message_;
    }

    private void initFields() {
      talkType_ = "";
      message_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTalkType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTalkTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, message_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTalkTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RESPONSE_SCRIPT_ERROR}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RESPONSE_SCRIPT_ERROR)
        cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROROrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cg.base.io.proto.ScriptProtos.internal_static_RESPONSE_SCRIPT_ERROR_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cg.base.io.proto.ScriptProtos.internal_static_RESPONSE_SCRIPT_ERROR_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR.class, cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR.Builder.class);
      }

      // Construct using cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        talkType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cg.base.io.proto.ScriptProtos.internal_static_RESPONSE_SCRIPT_ERROR_descriptor;
      }

      public cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR getDefaultInstanceForType() {
        return cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR.getDefaultInstance();
      }

      public cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR build() {
        cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR buildPartial() {
        cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR result = new cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.talkType_ = talkType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR) {
          return mergeFrom((cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR other) {
        if (other == cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR.getDefaultInstance()) return this;
        if (other.hasTalkType()) {
          bitField0_ |= 0x00000001;
          talkType_ = other.talkType_;
          onChanged();
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTalkType()) {
          
          return false;
        }
        if (!hasMessage()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_ERROR) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object talkType_ = "";
      /**
       * <code>required string talkType = 1;</code>
       */
      public boolean hasTalkType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string talkType = 1;</code>
       */
      public java.lang.String getTalkType() {
        java.lang.Object ref = talkType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            talkType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string talkType = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTalkTypeBytes() {
        java.lang.Object ref = talkType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          talkType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string talkType = 1;</code>
       */
      public Builder setTalkType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        talkType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string talkType = 1;</code>
       */
      public Builder clearTalkType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        talkType_ = getDefaultInstance().getTalkType();
        onChanged();
        return this;
      }
      /**
       * <code>required string talkType = 1;</code>
       */
      public Builder setTalkTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        talkType_ = value;
        onChanged();
        return this;
      }

      private int message_ ;
      /**
       * <code>required int32 message = 2;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 message = 2;</code>
       */
      public int getMessage() {
        return message_;
      }
      /**
       * <code>required int32 message = 2;</code>
       */
      public Builder setMessage(int value) {
        bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 message = 2;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RESPONSE_SCRIPT_ERROR)
    }

    static {
      defaultInstance = new RESPONSE_SCRIPT_ERROR(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RESPONSE_SCRIPT_ERROR)
  }

  public interface RESPONSE_SCRIPT_CHANGE_PALOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RESPONSE_SCRIPT_CHANGE_PAL)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 pal = 1;</code>
     */
    boolean hasPal();
    /**
     * <code>required int32 pal = 1;</code>
     */
    int getPal();

    /**
     * <code>required int32 time = 2;</code>
     */
    boolean hasTime();
    /**
     * <code>required int32 time = 2;</code>
     */
    int getTime();
  }
  /**
   * Protobuf type {@code RESPONSE_SCRIPT_CHANGE_PAL}
   */
  public static final class RESPONSE_SCRIPT_CHANGE_PAL extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RESPONSE_SCRIPT_CHANGE_PAL)
      RESPONSE_SCRIPT_CHANGE_PALOrBuilder {
    // Use RESPONSE_SCRIPT_CHANGE_PAL.newBuilder() to construct.
    private RESPONSE_SCRIPT_CHANGE_PAL(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RESPONSE_SCRIPT_CHANGE_PAL(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RESPONSE_SCRIPT_CHANGE_PAL defaultInstance;
    public static RESPONSE_SCRIPT_CHANGE_PAL getDefaultInstance() {
      return defaultInstance;
    }

    public RESPONSE_SCRIPT_CHANGE_PAL getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RESPONSE_SCRIPT_CHANGE_PAL(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              pal_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              time_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cg.base.io.proto.ScriptProtos.internal_static_RESPONSE_SCRIPT_CHANGE_PAL_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cg.base.io.proto.ScriptProtos.internal_static_RESPONSE_SCRIPT_CHANGE_PAL_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL.class, cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL.Builder.class);
    }

    public static com.google.protobuf.Parser<RESPONSE_SCRIPT_CHANGE_PAL> PARSER =
        new com.google.protobuf.AbstractParser<RESPONSE_SCRIPT_CHANGE_PAL>() {
      public RESPONSE_SCRIPT_CHANGE_PAL parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RESPONSE_SCRIPT_CHANGE_PAL(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RESPONSE_SCRIPT_CHANGE_PAL> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PAL_FIELD_NUMBER = 1;
    private int pal_;
    /**
     * <code>required int32 pal = 1;</code>
     */
    public boolean hasPal() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 pal = 1;</code>
     */
    public int getPal() {
      return pal_;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private int time_;
    /**
     * <code>required int32 time = 2;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 time = 2;</code>
     */
    public int getTime() {
      return time_;
    }

    private void initFields() {
      pal_ = 0;
      time_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, pal_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, time_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pal_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RESPONSE_SCRIPT_CHANGE_PAL}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RESPONSE_SCRIPT_CHANGE_PAL)
        cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PALOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cg.base.io.proto.ScriptProtos.internal_static_RESPONSE_SCRIPT_CHANGE_PAL_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cg.base.io.proto.ScriptProtos.internal_static_RESPONSE_SCRIPT_CHANGE_PAL_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL.class, cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL.Builder.class);
      }

      // Construct using cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cg.base.io.proto.ScriptProtos.internal_static_RESPONSE_SCRIPT_CHANGE_PAL_descriptor;
      }

      public cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL getDefaultInstanceForType() {
        return cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL.getDefaultInstance();
      }

      public cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL build() {
        cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL buildPartial() {
        cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL result = new cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pal_ = pal_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL) {
          return mergeFrom((cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL other) {
        if (other == cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL.getDefaultInstance()) return this;
        if (other.hasPal()) {
          setPal(other.getPal());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPal()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cg.base.io.proto.ScriptProtos.RESPONSE_SCRIPT_CHANGE_PAL) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int pal_ ;
      /**
       * <code>required int32 pal = 1;</code>
       */
      public boolean hasPal() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 pal = 1;</code>
       */
      public int getPal() {
        return pal_;
      }
      /**
       * <code>required int32 pal = 1;</code>
       */
      public Builder setPal(int value) {
        bitField0_ |= 0x00000001;
        pal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pal = 1;</code>
       */
      public Builder clearPal() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pal_ = 0;
        onChanged();
        return this;
      }

      private int time_ ;
      /**
       * <code>required int32 time = 2;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 time = 2;</code>
       */
      public int getTime() {
        return time_;
      }
      /**
       * <code>required int32 time = 2;</code>
       */
      public Builder setTime(int value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 time = 2;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RESPONSE_SCRIPT_CHANGE_PAL)
    }

    static {
      defaultInstance = new RESPONSE_SCRIPT_CHANGE_PAL(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RESPONSE_SCRIPT_CHANGE_PAL)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_REQUEST_SCRIPT_MUTUAL_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_REQUEST_SCRIPT_MUTUAL_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RESPONSE_SCRIPT_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RESPONSE_SCRIPT_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RESPONSE_SCRIPT_ERROR_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RESPONSE_SCRIPT_ERROR_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RESPONSE_SCRIPT_CHANGE_PAL_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RESPONSE_SCRIPT_CHANGE_PAL_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Script.proto\"D\n\025REQUEST_SCRIPT_MUTUAL\022" +
      "\013\n\003dir\030\001 \002(\005\022\r\n\002op\030\002 \001(\005:\0010\022\017\n\007message\030\003" +
      " \001(\t\"C\n\017RESPONSE_SCRIPT\022\020\n\010talkType\030\001 \002(" +
      "\t\022\017\n\007message\030\002 \002(\t\022\r\n\005infos\030\003 \003(\t\":\n\025RES" +
      "PONSE_SCRIPT_ERROR\022\020\n\010talkType\030\001 \002(\t\022\017\n\007" +
      "message\030\002 \002(\005\"7\n\032RESPONSE_SCRIPT_CHANGE_" +
      "PAL\022\013\n\003pal\030\001 \002(\005\022\014\n\004time\030\002 \002(\005B \n\020cg.bas" +
      "e.io.protoB\014ScriptProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_REQUEST_SCRIPT_MUTUAL_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_REQUEST_SCRIPT_MUTUAL_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_REQUEST_SCRIPT_MUTUAL_descriptor,
        new java.lang.String[] { "Dir", "Op", "Message", });
    internal_static_RESPONSE_SCRIPT_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RESPONSE_SCRIPT_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RESPONSE_SCRIPT_descriptor,
        new java.lang.String[] { "TalkType", "Message", "Infos", });
    internal_static_RESPONSE_SCRIPT_ERROR_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RESPONSE_SCRIPT_ERROR_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RESPONSE_SCRIPT_ERROR_descriptor,
        new java.lang.String[] { "TalkType", "Message", });
    internal_static_RESPONSE_SCRIPT_CHANGE_PAL_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RESPONSE_SCRIPT_CHANGE_PAL_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RESPONSE_SCRIPT_CHANGE_PAL_descriptor,
        new java.lang.String[] { "Pal", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
